<?php

/**
 * @file
 * Functions to support theming in the SASS Starterkit subtheme.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountProxyInterface;
use Drupal\user\Entity\User;




/**
 * Implements hook_form_system_theme_settings_alter() for  settings form.
 *
 * Replace Bootstrap setting options with subtheme ones.
 */
function bootstrap_sass_form_system_theme_settings_alter(&$form, FormStateInterface $form_state) {
  $form['components']['navbar']['bootstrap_navbar_top_background']['#options'] = array(
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  );
  $form['components']['navbar']['bootstrap_navbar_background']['#options'] = array(
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  );
}



/**
 * Implements hook_preprocess_page().
 */
function bootstrap_sass_preprocess_page(&$variables) {
  $currentUser = \Drupal::currentUser();

  if ($currentUser->isAuthenticated()) {
    $uid = $currentUser->id();
    $account = User::load($uid);

    if ($account) {
      $variables['current_user_name'] = $account->getDisplayName();

      if ($account->get('user_picture')->entity) {
        $variables['current_user_avatar'] = \Drupal::service('file_url_generator')
          ->generateString($account->get('user_picture')->entity->getFileUri());
      }
      else {
        $variables['current_user_avatar'] = '';
      }
    }
    $variables['#cache']['contexts'][] = 'user';
  }
}



/**
 * Get critical-front.css content to front page to improve speed. 
 */

use Drupal\Core\Theme\ThemeManagerInterface;

function bootstrap_sass_preprocess_html(array &$variables) {
  if (\Drupal::service('path.matcher')->isFrontPage()) {

    $theme_path = \Drupal::service('extension.path.resolver')
      ->getPath('theme', 'bootstrap_sass');

    $path = DRUPAL_ROOT . '/' . $theme_path . '/scss/critical-front.css';

    if (file_exists($path)) {
      $variables['critical_css'] = file_get_contents($path);
    }
  }
}


use Drupal\Core\Asset\AttachedAssets;

function bootstrap_sass_page_attachments_alter(array &$attachments) {
  if (!\Drupal::service('path.matcher')->isFrontPage()) {
    return;
  }

  if (empty($attachments['#attached']['css'])) {
    return;
  }

  foreach ($attachments['#attached']['css'] as $path => $options) {
    // Remove ONLY the heavy theme stylesheet
    if (str_contains($path, 'themes/custom/bootstraplak_sass/scss/style.css')) {
      unset($attachments['#attached']['css'][$path]);
    }
  }
}