<?php

/**
 * @file
 * Functions to support theming in the SASS Starterkit subtheme.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountProxyInterface;
use Drupal\user\Entity\User;




/**
 * Implements hook_form_system_theme_settings_alter() for settings form.
 *
 * Replace Bootstrap setting options with subtheme ones.
 */
function bootstrap_sass_form_system_theme_settings_alter(&$form, FormStateInterface $form_state) {
  $form['components']['navbar']['bootstrap_navbar_top_background']['#options'] = array(
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  );
  $form['components']['navbar']['bootstrap_navbar_background']['#options'] = array(
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  );
}



/**
 * Implements hook_preprocess_page().
 */
function bootstrap_sass_preprocess_page(&$variables) {
  $currentUser = \Drupal::currentUser();

  if ($currentUser->isAuthenticated()) {
    $uid = $currentUser->id();
    $account = User::load($uid);

    if ($account) {
      $variables['current_user_name'] = $account->getDisplayName();

      if ($account->get('user_picture')->entity) {
        $variables['current_user_avatar'] = \Drupal::service('file_url_generator')
          ->generateString($account->get('user_picture')->entity->getFileUri());
      }
      else {
        $variables['current_user_avatar'] = '';
      }
    }
    $variables['#cache']['contexts'][] = 'user';
  }
}
